-- AlterTable
ALTER TABLE `event` MODIFY `dateEnd` DATE NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `dateStart` DATE NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `timeEnd` TIME NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `timeStart` TIME NULL DEFAULT CURRENT_TIMESTAMP(3);

-- CreateTable
CREATE TABLE `Ticket` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `description` VARCHAR(191) NULL,
    `price` INTEGER NOT NULL,
    `status` ENUM('AVAILABLE', 'SOLD_OUT', 'CLOSED') NOT NULL DEFAULT 'AVAILABLE',
    `eventId` INTEGER NOT NULL,
    `startSale` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `endSale` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Ticket` ADD CONSTRAINT `Ticket_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `Event`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
